### ISSUE TITLE
THIS SUCKS 

### ISSUE THREAD

**Issue by dhiraj-patel** [roddarjohn/friendly-guacamole#1]
Mr. Rodda John you did not complete the hw, this is an issue that I will raise to your father. Mr. DW has been notified, and you have been ridiculed in period 6, publicly by Ely Sandine.

**Comment by roddarjohn** [comment]
Mr. Dhiraj Patel, I apologize.  I was not aware that this was a formal assignment -- it was not updated on the HW Google Doc until last night.  I will, of course, post my new style sheet shortly.  

I am closing this issue as I think I have dealt with it.
